#!/usr/bin/env python

# helper script that is shipped inside a bundled python package
# to launch the actual openmc binary which has to be inside the
# platlib part of the package so it can find the library via a
# rpath.

import subprocess
import sys

import pkg_resources

exe_file = pkg_resources.resource_filename("openmc", f"openmc_binary")

process = subprocess.Popen(
    [exe_file] + sys.argv[1:],
    stdout=sys.stdout,
    stderr=sys.stderr,
).communicate()
